### ISSUE TITLE
Components export props type that is not compatible with parameters

### ISSUE THREAD

**Issue by TatuLund** [vaadin/react-components#139]
Say, if I want to extend a component by wrapping it, I would like to avoid define props type again. Vaadin React components indeed export props type, like `Button` exports `ButtonProps`. However object of this type is not accepted as a parameter, hence the exported type does not have any purpose.

I would expect this to work

```
export function LinkButton(props: ButtonProps) {
  return (
    <Button {...props} theme="tertiary link" />
  );
}
```

But it does not

![image](https://github.com/vaadin/react-components/assets/14309836/fab36adf-fc4d-4869-be90-20b231d22c3d)

The workaround is to exclude the offending prop.

`export type LinkButtonProps = Omit<ButtonProps, 'dangerouslySetInnerHTML'>;`

**Comment by web-padawan** [comment]
This is no longer a problem with `@hilla/react-components` 2.3.0, possibly due to the Lit version bump:

## Before

<img width="726" alt="Screenshot 2023-12-13 at 13 41 30" src="https://github.com/vaadin/react-components/assets/10589913/294dd789-dbf3-4617-9bdd-ec14e75c7a67">

## After

<img width="847" alt="Screenshot 2023-12-13 at 13 41 54" src="https://github.com/vaadin/react-components/assets/10589913/9c0f08b2-96ba-490c-bc77-5df6d25f113b">

Closing this issue as fixed.
