### ISSUE TITLE
Prototype Interfaces removal from autocomplete

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/react-components#161]
As a part of this task we should prototype removal of Interfaces with cluttering properties / attributes from types while persisting the properties that are necessary for proper component behaviour.

We should also list the properties that are manually added back for future reference. It will also enable us to provide clarifications on the reasons of adding specific property.

**Comment by tomivirkki** [comment]
The issue will be fixed by https://github.com/vaadin/react-components/pull/167

The PR also fixes https://github.com/vaadin/react-components/issues/137 and https://github.com/vaadin/react-components/issues/150

> We should also list the properties that are manually added back for future reference. It will also enable us to provide clarifications on the reasons of adding specific property.

From the omitted HTMLElement properties, only [`autofocus` is currently manually added back](https://github.com/vaadin/react-components/pull/167/files#diff-be8ec7f14b9ef1eacfa935fdf1648234bec5b82573b58734a1870d6a9153235eR67), because some Vaadin web components also have [`autofocus` property](https://github.com/vaadin/web-components/blob/c7a300ee2ccfd4740ceaca58fa3358fa79ddb4f6/packages/a11y-base/src/delegate-focus-mixin.js#L25).

Note that the PR does not exclude properties from `HTMLElement` that are also included in `React.HTMLAttributes`

**Comment by rolfsmeds** [comment]
Closing as fixed by #167
