### ISSUE TITLE
Improve the TabSheet API

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#170]
The current way of using the `<TabSheet>` component is a bit clunky, since you have to pair a `<Tab>` and the content component together with an `id` (using the `tab` -helper function together with a spread operator).

```jsx
<TabSheet>
  <Tabs slot="tabs">
    <Tab id="dashboard-tab">Dashboard</Tab>
    <Tab id="payment-tab"><i>Payment</i></Tab>
  </Tabs>

  <div {...tab('dashboard-tab')}>This is the Dashboard tab content</div>
  <div {...tab('payment-tab')}>This is the Payment tab content</div>
</TabSheet>
```

Improve the `<TabSheet>` API by introducing a helper component (`<TabSheetTab>`) which abstracts away the underlying `id`-based pairing, for example:

```jsx
<TabSheet>
  <TabSheetTab header="Dashboard">
    <div>This is the Dashboard tab content</div>
  </TabSheetTab>

  <TabSheetTab header={<i>Payment</i>}>
    <div>This is the Payment tab content</div>
  </TabSheetTab>
</TabSheet>
```

The outcome in both cases:

![Screenshot 2023-12-20 at 10 42 48](https://github.com/vaadin/react-components/assets/1222264/6b4af148-dcff-4ed9-b767-b436b5c65313)

Prototype at https://github.com/vaadin/react-components/tree/feat/tabsheet-api

**Comment by tomivirkki** [comment]
Any opinions on the suggested API or alternative suggestions @rolfsmeds @marcushellberg @sissbruecker? Not sure if `header` is the proper term for what defines the content placed inside the tab

**Comment by sissbruecker** [comment]
The API makes sense IMO. I checked some other libraries for comparison:
- [MUI](https://mui.com/material-ui/react-tabs/) only has a variant of our `Tabs`, where you need to toggle the content, and handle the correlation between tab and content, manually. So not really comparable.
- [Ant Design](https://ant.design/components/tabs) has a tab sheet variant, they use an `items` prop to configure the individual tabs and their contents. I like the declarative approach you suggested here better. 
- [Chakra](https://chakra-ui.com/docs/components/tabs) also has a tab sheet variant, but separates tabs and sheets into separate containers, and then seems to use the index for correlation under the hood. I would prefer declaring tab and content in the same component as suggested here.

As for the tab header / title, at least MUI and Ant Design use `label`, so that could be an alternative. But `header` is fine too IMO.

**Comment by sissbruecker** [comment]
One thing that might get tricky is if you need to set any other prop on either/both the tab or the content panel, like `aria-*` maybe. Though I don't know if there is a use case.

**Comment by rolfsmeds** [comment]
Like @sissbruecker, I would propose `label` rather than `header`.

As for additional attributes, tabs already have a property for `aria-label` IIRC, and I don't think the sheet needs one as you can place that on its contents instead of needed.

Icons, though?

**Comment by tomivirkki** [comment]
Thanks for the feedback. Pushed an update to the [prototype](https://github.com/vaadin/react-components/tree/feat/tabsheet-api) with `header` renamed to `label`.

The props of a `<TabSheetTab>` now get passed to the underlying underlying `<Tab>` so you can add aria-* attributes etc.

The `label` accepts any type of a `ReactNode` so icons shouldn't be a problem either.

```jsx
<TabSheet>
  <div slot="prefix">PREFIX</div>

  <TabSheetTab label="Dashboard" aria-label="dashboard">
    <div>This is the Dashboard tab content</div>
  </TabSheetTab>

  <TabSheetTab
    label={
      <>
        <Icon icon="vaadin:user" />
        <i>Payment</i>
      </>
    }
  >
    <div>This is the Payment tab content</div>
  </TabSheetTab>

  <div slot="suffix">SUFFIX</div>
</TabSheet>
```

Renders as:

![Screenshot 2023-12-20 at 12 54 37](https://github.com/vaadin/react-components/assets/1222264/20f7309d-b0d1-455b-85ec-2c691e79ce56)

Note that this change does not disable the existing API but adds an alternative one on top of it.
