### ISSUE TITLE
Improve IDE autocomplete behaviour

### ISSUE THREAD

**Issue by platosha** [vaadin/react-components#49]
Both VS Code and IDEA seem to have issues with autocomplete for React components.

Steps to reproduce:

1. Create project with CLI
2. Start project
3. Add a `<ComboBox/>` to a view, using autocomplete to do the import
  - VS Code does not offer any autocomplete. No import -> does not compile.
  - IntelliJ autocompletes all the attributes in Combobox, but leaves the tag open and fails to add the needed `.js` to the import -> does not compile.

**Comment by marcushellberg** [comment]
Another autocomplete-related issue is that for some components, like ComboBox, IntelliJ lists every single attribute when auto-completing. Other components do not have this issue. 

This is what the issue looks like:
https://user-images.githubusercontent.com/883698/208738417-a98824fd-1237-4a6b-b6be-589b931ecf30.mp4

It seems to be caused by IntelliJ thinking that every attribute is required:
<img width="1184" alt="required-attributes" src="https://user-images.githubusercontent.com/883698/208738428-fb01f122-8ee1-435a-a4e5-97c62e67a75b.png">

**Comment by web-padawan** [comment]
Confirmed the issue with VSCode. Also, when trying `Com` to search for `ComboBox` I get `WebComponentModule` suggestions:

![Screenshot 2022-12-20 at 20 26 42](https://user-images.githubusercontent.com/10589913/208739399-7d1c5f91-e4e2-493e-be0c-da176952ea54.png)

Note: tried [TypeScript Importer](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter) plugin for VS Code and it didn't help.

**Comment by marcushellberg** [comment]
I did not have these issues with the earlier proof of concept, and I don't believe I had the issue with alphas either. In case that helps narrow down the possibilities.

**Comment by platosha** [comment]
The VS Code had trouble finding typescript definitions due to a missing package index. This was addressed in https://github.com/vaadin/react-components/pull/50

Another issue is autocomplete in IDEA. Turns out, it’s a side effect of declaring props using `Omit<....>`, that for some reason only affects IntelliJ IDEA. https://github.com/vaadin/react-components/pull/56 should have fixed this by making all the props explicitly optional using `Partial<Omit<...>>`.
