### ISSUE TITLE
`GridColumn` is exported from both `Grid.js` and `GridColumn.js`

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#68]
Having those two exports is visible in import suggestions and the wrong one is selected as first.

**Comment by platosha** [comment]
The export originates from the `https://github.com/vaadin/web-components/blob/main/packages/grid/vaadin-grid.js` file, which combines grid and grid-column exports together. Note that we cannot simply replace with `src` import because that will skip the default Lumo styles.

Importing `GridColumn` web component class instead of the React component as a result of auto-import is very annoying.
