### ISSUE TITLE
Custom editor renderer not working correctly in Grid Pro

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#75]
I'm trying to translate this to React:
```html
        <vaadin-grid-pro-edit-column
          path="birthday"
          ${columnBodyRenderer<Person>(
            ({ birthday }) => html`${format(parseISO(birthday), 'MM/dd/yyyy')}`,
            []
          )}
          ${columnEditModeRenderer<Person>(
            ({ birthday }) =>
              html`
                <vaadin-date-picker style="width: 100%" .value="${birthday}"></vaadin-date-picker>
              `,
            []
          )}
        ></vaadin-grid-pro-edit-column>
```
The best I could do is:
```tsx
      <GridProEditColumn
        path="birthday"
        renderer={(item) => (
          <>{format(parseISO(item.item.birthday), "dd/MM/yyyy")}</>
        )}
        editModeRenderer={(item) => (
          <DatePicker style={{ width: "100%" }} value={item.item.birthday} />
        )}
      />
```
But I get error:
```
Uncaught TypeError: editor is null
    _startCellEdit vaadin-grid-pro-edit-column.js:279
    _startEdit vaadin-grid-pro-inline-editing-mixin.js:338
    _enterEditFromEvent vaadin-grid-pro-inline-editing-mixin.js:292
    ready vaadin-grid-pro-inline-editing-mixin.js:161
    ready vaadin-grid-pro-inline-editing-mixin.js:159
```
https://github.com/cromoteca/component-docs/blob/3ab3b818c77a45fdec218695017b72333e816f27/frontend/views/grid-pro/GridProEditors.tsx#L23-L31

**Comment by web-padawan** [comment]
The issue is still valid. Starting cell editing for the first time works fine, but after stopping edit the custom component (in this case `TextField`) does not get unmounted by React. So trying to edit the same cell for the second time causes an error.

I'm still trying to find a way to approach this. We need to cleanup component created by `editModeRenderer` somehow, as the cell content `innerHTML` is [cleared](https://github.com/vaadin/web-components/blob/cbfe9dac7adcb3e539da5ea89ae2105955c40115/packages/grid/src/vaadin-grid-column-mixin.js#L649-L654) by the column and React doesn't know about it.

**Comment by tomivirkki** [comment]
Did some investigation on this and discovered a couple of potential ways to fixing this.

[Option 1](https://github.com/vaadin/react-components/tree/fix/grid-pro/custom-edit-renderer): Add a unique `key` for the (edit- and body-) renderer content to have it re-initialized on every invocation. It's quite hacky and may only work with a function renderer.

[Option 2](https://github.com/vaadin/react-components/tree/fix/grid-pro/custom-edit-renderer-2): Use `createRoot` instead of portals for the renderers that target the same content element. This will render the cell content to separate roots which may not be ideal.

Both require a nasty monkey patch of the content element's native `removeChild` function to avoid an error while React tries to remove the editor element that has already been removed by grid-pro.
